from frappe.custom.doctype.custom_field.custom_field import create_custom_fields

def execute():
    custom_fields = {
        'BOM': [
            {"fieldtype": "Currency", "label": "KG Selling Total BOM Amount", "fieldname": "custom_kg_selling_total_bom_amount", "insert_after": "custom_kg_selling_making_charge"},
            {"fieldtype": "Currency", "label": "KG Selling Making Charge", "fieldname": "custom_kg_selling_making_charge", "insert_after": "custom_kg_selling_other_bom_amount"},
            {"fieldtype": "Currency", "label": "KG Selling Other BOM Amount", "fieldname": "custom_kg_selling_other_bom_amount", "insert_after": "custom_kg_selling_finding_bom_amount"},
            {"fieldtype": "Currency", "label": "KG Selling Finding BOM Amount", "fieldname": "custom_kg_selling_finding_bom_amount", "insert_after": "custom_column_break_1zlxx"},
            {"fieldtype": "Column Break", "fieldname": "custom_column_break_1zlxx", "insert_after": "custom_kg_selling_gemstone_bom_amount"},
            {"fieldtype": "Currency", "label": "KG Selling Gemstone BOM Amount", "fieldname": "custom_kg_selling_gemstone_bom_amount", "insert_after": "custom_kg_selling_diamond_bom_amount"},
            {"fieldtype": "Currency", "label": "KG Selling Diamond BOM amount", "fieldname": "custom_kg_selling_diamond_bom_amount", "insert_after": "custom_kg_selling_gold_bom_amount"},
            {"fieldtype": "Currency", "label": "KG Selling Gold Bom Amount", "fieldname": "custom_kg_selling_gold_bom_amount", "insert_after": "custom_kg_selling_rate"},
            {"fieldtype": "Section Break", "label": "KG Selling Rate", "fieldname": "custom_kg_selling_rate", "insert_after": "custom_kg_cost_total_bom_amount", "collapsible": 1},
            {"fieldtype": "Currency", "label": "KG Cost Total BOM Amount", "fieldname": "custom_kg_cost_total_bom_amount", "insert_after": "custom_kg_cost_making_charge"},
            {"fieldtype": "Currency", "label": "KG Cost Making Charge", "fieldname": "custom_kg_cost_making_charge", "insert_after": "custom_kg_cost_other_bom_amount"},
            {"fieldtype": "Currency", "label": "KG Cost Other BOM Amount", "fieldname": "custom_kg_cost_other_bom_amount", "insert_after": "custom_kg_cost_finding_bom_amount"},
            {"fieldtype": "Currency", "label": "KG Cost Finding BOM Amount", "fieldname": "custom_kg_cost_finding_bom_amount", "insert_after": "custom_column_break_ppa4s"},
            {"fieldtype": "Column Break", "fieldname": "custom_column_break_ppa4s", "insert_after": "custom_kg_cost_gemstone_bom_amount"},
            {"fieldtype": "Currency", "label": "KG Cost Gemstone BOM Amount", "fieldname": "custom_kg_cost_gemstone_bom_amount", "insert_after": "custom_kg_cost_diamond_bom_amount"},
            {"fieldtype": "Currency", "label": "KG Cost Diamond BOM amount", "fieldname": "custom_kg_cost_diamond_bom_amount", "insert_after": "custom_kg_cost_gold_bom_amount"},
            {"fieldtype": "Currency", "label": "KG Cost Gold Bom Amount", "fieldname": "custom_kg_cost_gold_bom_amount", "insert_after": "custom_kg_cost_rate"},
            {"fieldtype": "Section Break", "label": "KG Cost Rate", "fieldname": "custom_kg_cost_rate", "insert_after": "custom_gk_sell_total_bom_amount", "collapsible": 1},
            {"fieldtype": "Currency", "label": "GK Sell Total BOM Amount", "fieldname": "custom_gk_sell_total_bom_amount", "insert_after": "custom_gk_sell_making_charge"},
            {"fieldtype": "Currency", "label": "GK Sell Making Charge", "fieldname": "custom_gk_sell_making_charge", "insert_after": "custom_gk_sell_other_bom_amount"},
            {"fieldtype": "Currency", "label": "GK Sell Other BOM Amount", "fieldname": "custom_gk_sell_other_bom_amount", "insert_after": "custom_gk_sell_finding_bom_amount"},
            {"fieldtype": "Currency", "label": "GK Sell Finding BOM Amount", "fieldname": "custom_gk_sell_finding_bom_amount", "insert_after": "custom_column_break_wx3rt"},
            {"fieldtype": "Column Break", "fieldname": "custom_column_break_wx3rt", "insert_after": "custom_gk_sell_gemstone_bom_amount"},
            {"fieldtype": "Currency", "label": "GK Sell Gemstone BOM Amount", "fieldname": "custom_gk_sell_gemstone_bom_amount", "insert_after": "custom_gk_sell_diamond_bom_amount"},
            {"fieldtype": "Currency", "label": "GK Sell Diamond BOM amount", "fieldname": "custom_gk_sell_diamond_bom_amount", "insert_after": "custom_gk_sell_gold_bom_amount"},
            {"fieldtype": "Currency", "label": "GK Sell Gold Bom Amount", "fieldname": "custom_gk_sell_gold_bom_amount", "insert_after": "custom_gk_selling_rate"},
            {"fieldtype": "Section Break", "label": "GK Selling Rate", "fieldname": "custom_gk_selling_rate", "insert_after": "custom_gk_cost_total_bom_amount", "collapsible": 1},
            {"fieldtype": "Currency", "label": "Gk Cost Total BOM Amount", "fieldname": "custom_gk_cost_total_bom_amount", "insert_after": "custom_gk_cost_making_charge"},
            {"fieldtype": "Currency", "label": "Gk Cost Making Charge", "fieldname": "custom_gk_cost_making_charge", "insert_after": "custom_gk_cost_other_bom_amount"},
            {"fieldtype": "Currency", "label": "Gk Cost Other BOM Amount", "fieldname": "custom_gk_cost_other_bom_amount", "insert_after": "custom_gk_cost_finding_bom_amount"},
            {"fieldtype": "Currency", "label": "Gk Cost Finding BOM Amount", "fieldname": "custom_gk_cost_finding_bom_amount", "insert_after": "custom_column_break_4yxj1"},
            {"fieldtype": "Column Break", "fieldname": "custom_column_break_4yxj1", "insert_after": "custom_gk_cost_gemstone_bom_amount"},
            {"fieldtype": "Currency", "label": "Gk Cost Gemstone BOM Amount", "fieldname": "custom_gk_cost_gemstone_bom_amount", "insert_after": "custom_gk_cost_diamond_bom_amount"},
            {"fieldtype": "Currency", "label": "Gk Cost Diamond BOM amount", "fieldname": "custom_gk_cost_diamond_bom_amount", "insert_after": "custom_gk_cost_gold_bom_amount"},
            {"fieldtype": "Currency", "label": "Gk Cost Gold Bom Amount", "fieldname": "custom_gk_cost_gold_bom_amount", "insert_after": "custom_gk_costing_rate"},
            {"fieldtype": "Section Break", "label": "Gk Costing Rate", "fieldname": "custom_gk_costing_rate", "insert_after": "total_bom_amount", "collapsible": 1},
        ],
    }
    create_custom_fields(custom_fields)
