import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields


def execute():
	create_custom_fields(
		{
			"Stock Entry": [
				dict(
					fieldname="custom_pc_tagging_sync_hash",
					fieldtype="Data",
					label="PC Tagging Sync Hash",
					insert_after="auto_created",
					hidden=1,
					read_only=1,
					no_copy=1,
					search_index=1,
				),
				dict(
					fieldname="custom_pc_tagging_scenario",
					fieldtype="Data",
					label="PC Tagging Scenario",
					insert_after="custom_pc_tagging_sync_hash",
					hidden=1,
					read_only=1,
					no_copy=1,
				),
				dict(
					fieldname="custom_pc_tagging_movement_type",
					fieldtype="Data",
					label="PC Tagging Movement Type",
					insert_after="custom_pc_tagging_scenario",
					hidden=1,
					read_only=1,
					no_copy=1,
				),
			],
			"Stock Entry Detail": [
				dict(
					fieldname="custom_source_mop_log",
					fieldtype="Data",
					label="Source MOP Log",
					insert_after="manufacturing_operation",
					hidden=1,
					read_only=1,
					no_copy=1,
				),
				dict(
					fieldname="custom_employee_ir_manual_loss_row",
					fieldtype="Data",
					label="Employee IR Manual Loss Row",
					insert_after="custom_source_mop_log",
					hidden=1,
					read_only=1,
					no_copy=1,
				),
				dict(
					fieldname="custom_loss_type",
					fieldtype="Data",
					label="Loss Type (PC Sync)",
					insert_after="custom_employee_ir_manual_loss_row",
					hidden=1,
					read_only=1,
					no_copy=1,
				),
				dict(
					fieldname="custom_loss_item",
					fieldtype="Data",
					label="Loss Item (PC Sync)",
					insert_after="custom_loss_type",
					hidden=1,
					read_only=1,
					no_copy=1,
				),
				dict(
					fieldname="custom_pc_tagging_line_hash",
					fieldtype="Data",
					label="PC Tagging Line Hash",
					insert_after="custom_loss_item",
					hidden=1,
					read_only=1,
					no_copy=1,
				),
			],
			"Stock Reservation Entry": [
				dict(
					fieldname="custom_pc_tagging_sync_hash",
					fieldtype="Data",
					label="PC Tagging Sync Hash",
					insert_after="manufacturing_operation",
					hidden=1,
					read_only=1,
					no_copy=1,
					search_index=1,
				),
				dict(
					fieldname="custom_department_ir",
					fieldtype="Data",
					label="Department IR",
					insert_after="custom_pc_tagging_sync_hash",
					hidden=1,
					read_only=1,
					no_copy=1,
				),
				dict(
					fieldname="custom_replaced_sre",
					fieldtype="Data",
					label="Replaced SRE",
					insert_after="custom_department_ir",
					hidden=1,
					read_only=1,
					no_copy=1,
				),
				dict(
					fieldname="custom_replaced_sre_snapshot",
					fieldtype="Long Text",
					label="Replaced SRE Snapshot (JSON)",
					insert_after="custom_replaced_sre",
					hidden=1,
					read_only=1,
					no_copy=1,
				),
				dict(
					fieldname="custom_pc_tagging_scenario",
					fieldtype="Data",
					label="PC Tagging Scenario",
					insert_after="custom_replaced_sre_snapshot",
					hidden=1,
					read_only=1,
					no_copy=1,
				),
				dict(
					fieldname="custom_pc_tagging_movement_type",
					fieldtype="Data",
					label="PC Tagging Movement Type",
					insert_after="custom_pc_tagging_scenario",
					hidden=1,
					read_only=1,
					no_copy=1,
				),
			],
		},
		ignore_validate=True,
	)
