"""GATED re-shard of Gurukrupa Stock Entry naming (F-001, the ~74% lever).

Problem
-------
Every Gurukrupa Export Stock Entry names off the SINGLE ``tabSeries`` row
``MAT-STE-`` because Gurukrupa's own per-(company x type) Document Naming Rules
(``GE-SE-*``, 41 of them) were DISABLED, dumping ~193k SEs onto one counter row.
That one row is the victim of ~74% of all production 1205/1213 lock errors. KG GK
Jewellers, by contrast, keeps its ``KGJPL-SE-*`` rules ACTIVE and is already spread
across ~40 counters. Re-enabling Gurukrupa's rules spreads its naming the same way
(~40x drop in per-row contention) and restores readable, type-encoded numbers.

Why this is a GATED, MANUAL patch (NOT wired into patches.txt)
-------------------------------------------------------------
1. **Business sign-off**: re-enabling changes new Gurukrupa SE numbers from
   ``MAT-STE-######`` back to ``GE-SE-<type>-<yy>-#####``. Confirm WHY the rules were
   disabled (deliberate? accidental? a prior migration?) before flipping them.
2. **Duplicate-name risk**: a Document Naming Rule counter is a single integer on the
   rule row. Its historical ``GE-SE-*`` names (~76k) were generated before it was
   disabled; if the counter sits below the max historical suffix, the next generated
   name would COLLIDE with an existing primary key. This patch seeds each counter to
   ``GREATEST(current, max existing suffix for that rule's prefix)`` so it can only go
   forward -- but that seeding MUST be reviewed on a copy site first.

Therefore ``execute()`` (the migrate entrypoint) intentionally no-ops. Run the real
work explicitly, dry-run FIRST:

    bench --site <site> execute jewellery_erpnext.patches.reshard_gurukrupa_stock_entry_naming.reshard
    # review the per-rule report (current counter / max existing suffix / would-seed-to),
    # verify no counter needs to move backwards, confirm on a copy site, THEN:
    bench --site <site> execute jewellery_erpnext.patches.reshard_gurukrupa_stock_entry_naming.reshard --kwargs "{'confirm': True}"

Reversible: re-disable the same rules with ``rollback()`` below (counters are left as
seeded -- forward-only -- which is safe).

Companion: ``lock_order.preallocate_series_for_docs`` already pins the Document Naming
Rule counter in canonical order (the F-003 fix), so the re-sharded counters are also
pre-lockable -- no separate change needed there.
"""

import frappe

_COMPANY = "Gurukrupa Export Private Limited"


def _target_rules(company):
	"""Disabled Stock Entry Document Naming Rules whose conditions bind to ``company``."""
	rules = frappe.get_all(
		"Document Naming Rule",
		filters={"document_type": "Stock Entry", "disabled": 1},
		fields=["name", "prefix", "prefix_digits", "counter", "priority"],
	)
	targeted = []
	for r in rules:
		conds = frappe.get_all(
			"Document Naming Rule Condition",
			filters={"parent": r.name},
			fields=["field", "condition", "value"],
		)
		if any(c.field == "company" and (c.value or "") == company for c in conds):
			targeted.append((r, conds))
	return targeted


def _prefix_stem(prefix):
	"""Literal name stem a rule's prefix produces, i.e. the part before the first date/
	field token. ``GE-SE-MTWO-.YY.-`` -> ``GE-SE-MTWO-``. Used to LIKE-match existing
	names when computing the max suffix already generated by this rule."""
	return (prefix or "").split(".")[0]


def _max_existing_suffix(stem):
	if not stem:
		return 0
	row = frappe.db.sql(
		"""
		SELECT MAX(CAST(REGEXP_SUBSTR(`name`, '[0-9]+$') AS UNSIGNED))
		FROM `tabStock Entry`
		WHERE `name` LIKE %s AND `name` REGEXP '[0-9]+$'
		""",
		(stem + "%",),
	)
	return int(row[0][0] or 0)


def reshard(company=None, confirm=False):
	"""Dry-run (default) or apply the Gurukrupa Stock Entry naming re-shard.

	confirm=False -> print a per-rule report, change nothing.
	confirm=True  -> seed each counter to GREATEST(current, max existing suffix) and
	                 set disabled=0, then commit.
	"""
	company = company or _COMPANY
	targeted = _target_rules(company)
	if not targeted:
		print(
			f"[reshard] No disabled Stock Entry naming rules bound to company {company!r}."
		)
		return

	print(
		f"[reshard] {len(targeted)} disabled rule(s) for {company!r}. confirm={confirm}"
	)
	print(f"{'rule':<24} {'prefix':<22} {'counter':>8} {'max_seen':>9} {'seed_to':>8}")
	changed = 0
	for r, _conds in targeted:
		stem = _prefix_stem(r.prefix)
		max_seen = _max_existing_suffix(stem)
		seed_to = max(int(r.counter or 0), max_seen)
		print(
			f"{r.name:<24} {(r.prefix or ''):<22} {int(r.counter or 0):>8} {max_seen:>9} {seed_to:>8}"
		)
		if confirm:
			if seed_to != int(r.counter or 0):
				frappe.db.set_value(
					"Document Naming Rule",
					r.name,
					"counter",
					seed_to,
					update_modified=False,
				)
			frappe.db.set_value(
				"Document Naming Rule", r.name, "disabled", 0, update_modified=False
			)
			frappe.get_doc("Document Naming Rule", r.name).clear_doctype_map()
			changed += 1

	if confirm:
		frappe.db.commit()
		print(
			f"[reshard] APPLIED: seeded + re-enabled {changed} rule(s). New Gurukrupa "
			f"Stock Entries will name off GE-SE-<type>-<yy>-#####."
		)
	else:
		print(
			"[reshard] DRY-RUN only -- nothing changed. Re-run with confirm=True to apply."
		)


def rollback(company=None):
	"""Re-disable the rules (counters left forward-only, which is safe)."""
	company = company or _COMPANY
	for r, _conds in _target_rules_enabled(company):
		frappe.db.set_value(
			"Document Naming Rule", r.name, "disabled", 1, update_modified=False
		)
		frappe.get_doc("Document Naming Rule", r.name).clear_doctype_map()
	frappe.db.commit()
	print(f"[reshard] Rolled back: re-disabled Gurukrupa rules for {company!r}.")


def _target_rules_enabled(company):
	rules = frappe.get_all(
		"Document Naming Rule",
		filters={"document_type": "Stock Entry", "disabled": 0},
		fields=["name", "prefix"],
	)
	out = []
	for r in rules:
		conds = frappe.get_all(
			"Document Naming Rule Condition",
			filters={"parent": r.name},
			fields=["field", "value"],
		)
		if any(c.field == "company" and (c.value or "") == company for c in conds):
			out.append((r, conds))
	return out


def execute():
	"""Migrate entrypoint intentionally no-ops -- this is a gated manual migration.

	(Kept importable/safe so an accidental patches.txt wiring cannot flip production
	naming. Run ``reshard`` explicitly after business sign-off; see module docstring.)"""
	frappe.logger("jewellery_erpnext").info(
		"reshard_gurukrupa_stock_entry_naming: gated manual patch; execute() no-ops. "
		"Run the `reshard` function explicitly after sign-off."
	)
